import discord
import requests

from discord.ext import commands
from discord import app_commands
from bs4 import BeautifulSoup

embed = discord.Embed(color=0xecc98e)
embed.set_footer(text="Image generated by BoredHumans, https://boredhumans.com/")

# Used to get AI images from the website, https://boredhumans.com/, check it out!

#NOTE: Each webpage is structured differently, so it is not exactly possible to make each command the same.
class Generate(commands.GroupCog, group_name = "generate"):
    def __init__(self, bot : commands.Bot):
        super().__init__()
        self.bot = bot

    @app_commands.command(name="waifu", description="Have an AI generate a waifu, they do not exist sadly.")
    async def _gen_waifu(self, interaction : discord.Interaction):
        await interaction.response.defer()
        req = requests.get("http://boredhumans.com/anime_images.php")
        soup = BeautifulSoup(req.content, "html.parser")
        images = soup.findAll("img")
        result = embed.copy()

        for img in images:
            if "anime" in img["src"]:
                result.set_image(url=img["src"])
                break

        await interaction.followup.send(embed=result)

    @app_commands.command(name="quote", description="Have an AI generate a quote, maybe they're inspiring.")
    async def _gen_quote(self, interaction : discord.Interaction):
        await interaction.response.defer()
        req = requests.get("https://boredhumans.com/quotes.php")
        soup = BeautifulSoup(req.content, "html.parser")
        images = soup.findAll("img")
        result = embed.copy()

        for img in images:
            if "quote" in img["src"]:
                result.set_image(url=img["src"])
                break

        await interaction.followup.send(embed=result)

    @app_commands.command(name="pizza", description="Have an AI generate a pizza for you.")
    async def _gen_pizza(self, interaction: discord.Interaction):
        await interaction.response.defer()
        req = requests.get("https://boredhumans.com/pizza.php")
        soup = BeautifulSoup(req.content, "html.parser")
        images = soup.findAll("img")
        result = embed.copy()

        for img in images:
            if "pizza" in img["src"]:
                result.set_image(url=img["src"])
                break

        await interaction.followup.send(embed=result)

async def setup(bot: commands.Bot):
    await bot.add_cog(Generate(bot))




